// Generated by CoffeeScript 1.6.3
/*
 * Jidoteki - https://jidoteki.com
 * Build virtual appliances using Jidoteki
 * Copyright (c) 2014 Alex Williams, Unscramble <license@unscramble.jp>
*/


(function() {
  var api, armrest, crypto, settings,
    _this = this,
    __slice = [].slice;

  crypto = require('crypto');

  armrest = require('armrest');

  settings = {
    endpoint: 'https://api.jidoteki.com',
    userid: process.env.JIDOTEKI_USERID || 'change me',
    apikey: process.env.JIDOTEKI_APIKEY || 'change me',
    useragent: 'nodeclient-jidoteki/0.1.5',
    token: null
  };

  api = armrest.client(settings.endpoint);

  exports.settings = settings;

  exports.makeHMAC = function(string, callback) {
    return callback(crypto.createHmac('sha256', settings.apikey).update(string).digest('hex'));
  };

  exports.getToken = function(callback) {
    var resource;
    resource = '/auth/user';
    return this.makeHMAC("POST" + settings.endpoint + resource, function(signature) {
      return api.post({
        url: resource,
        headers: {
          'X-Auth-Uid': settings.userid,
          'X-Auth-Signature': signature,
          'User-Agent': settings.useragent,
          'Accept-Version': 1,
          'Content-Type': 'application/json'
        },
        complete: function(err, res, data) {
          if (data.status === 'success') {
            settings.token = data.content;
            setTimeout(function() {
              return settings.token = null;
            }, 27000000);
          }
          return callback(data);
        }
      });
    });
  };

  exports.getData = function(resource, callback) {
    return this.makeHMAC("GET" + settings.endpoint + resource, function(signature) {
      return api.get({
        url: resource,
        headers: {
          'X-Auth-Token': settings.token,
          'X-Auth-Signature': signature,
          'User-Agent': settings.useragent,
          'Accept-Version': 1
        },
        complete: function(err, res, data) {
          if (err) {
            if (data.status === 'error' && data.message === 'Unable to authenticate') {
              settings.token = null;
            }
          }
          return callback(data);
        }
      });
    });
  };

  exports.postData = function(resource, string, callback) {
    return this.makeHMAC("POST" + settings.endpoint + resource + (JSON.stringify(string)), function(signature) {
      console.log(string);
      return api.post({
        url: resource,
        params: string,
        headers: {
          'X-Auth-Token': settings.token,
          'X-Auth-Signature': signature,
          'User-Agent': settings.useragent,
          'Accept-Version': 1,
          'Content-Type': 'application/json'
        },
        complete: function(err, res, data) {
          if (err) {
            if (data.status === 'error' && data.message === 'Unable to authenticate') {
              settings.token = null;
            }
          }
          return callback(data);
        }
      });
    });
  };

  exports.makeRequest = function() {
    var apiCall, callback, method, requestMethod, resource, string, _i;
    requestMethod = arguments[0], resource = arguments[1], string = 4 <= arguments.length ? __slice.call(arguments, 2, _i = arguments.length - 1) : (_i = 2, []), callback = arguments[_i++];
    method = requestMethod.toUpperCase();
    apiCall = function() {
      switch (method) {
        case "GET":
          return _this.getData(resource, function(result) {
            return callback(result);
          });
        case "POST":
          return _this.postData(resource, string[0], function(result) {
            return callback(result);
          });
      }
    };
    if (settings.token != null) {
      return apiCall();
    } else {
      return _this.getToken(function(result) {
        if (result.status === 'success') {
          return apiCall();
        } else {
          return callback(result);
        }
      });
    }
  };

}).call(this);
